In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#loading the dataframe
df= pd.read_csv(r"/content/AirQualityUCI.csv")

In [ ]:
df.head()

                                                                                                            Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
10/03/2004;18.00.00;2            6;1360;150;11                 9;1046;166;1056;113;1692;1268;13 6;48 9;0                                                7578;;
10/03/2004;19.00.00;2;1292;112;9 4;955;103;1174;92;1559;972;13 3;47                             7;0  7255;;                                                NaN
10/03/2004;20.00.00;2            2;1402;88;9                   0;939;131;1140;114;1555;1074;11  9;54 0;0                                                7502;;
10/03/2004;21.00.00;2            2;1376;80;9                   2;948;172;1092;122;1584;1203;11  0;60 0;0                                                7867;;
10/03/2004;22.00.00;1            6;1272;51;6                   5;836;131;1205;116;1490;1110;11  2;59 6;0                                                7888;;

In [ ]:
df_who = pd.read_csv(r"/content/ML_WHO_DATASET1.csv")

In [ ]:
df_who.head()

,who_region,iso3,country_name,city,year,version,pm10_concentration,pm25_concentration,no2_concentration,pm10_tempcov,pm25_tempcov,no2_tempcov,type_of_stations,reference,web_link,population,population_source,latitude,longitude,who_ms
0,4_Eur,ESP,Spain,A Coruna/ESP,2013.0,"V4.0 (2018), V4.0 (2018), V4.0 (2018), V4.0 (2...",23.238,11.491,28.841,87.0,46.0,93.0,"Urban, Urban, Suburban",NaN,NaN,246146.0,"manual, manual, manual, manual",43.367900,-8.418571,1
1,4_Eur,ESP,Spain,A Coruna/ESP,2014.0,"V6.0 (2023), V6.0 (2023), V6.0 (2023)",27.476,15.878,19.575,96.0,88.0,95.0,"Urban, Urban, Suburban",NaN,NaN,247604.0,NaN,43.368033,-8.418233,1
2,4_Eur,ESP,Spain,A Coruna/ESP,2015.0,"V6.0 (2023), V6.0 (2023), V6.0 (2023), V6.0...",25.515,14.004,22.731,98.0,71.0,98.0,"Urban, Urban, Suburban, Suburban",NaN,NaN,247604.0,NaN,43.370375,-8.422900,1
3,4_Eur,ESP,Spain,A Coruna/ESP,2016.0,"V6.0 (2023), V6.0 (2023), V6.0 (2023), V6.0...",23.057,13.160,20.204,98.0,98.0,98.0,"Urban, Urban, Suburban, Suburban",NaN,NaN,247604.0,NaN,43.370375,-8.422900,1
4,4_Eur,ESP,Spain,A Coruna/ESP,2017.0,"V6.0 (2023), V6.0 (2023), V6.0 (2023), V6.0...",26.849,14.114,21.543,97.0,97.0,98.0,"Urban, Urban, Suburban, Suburban",NaN,NaN,247604.0,NaN,43.370375,-8.422900,1

In [ ]:
df1=pd.read_csv(r"/content/ML_WHO_DATASET1.csv")

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40098 entries, 0 to 40097
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   who_region          40098 non-null  object
 1   iso3                40098 non-null  object
 2   country_name        40098 non-null  object
 3   city                40098 non-null  object
 4   year                40098 non-null  int64
 5   version             40098 non-null  object
 6   pm10_concentration  28672 non-null  float64
 7   pm25_concentration  21730 non-null  float64
 8   no2_concentration   26934 non-null  float64
 9   pm10_tempcov        22403 non-null  float64
 10  pm25_tempcov        16590 non-null  float64
 11  no2_tempcov         23402 non-null  float64
 12  type_of_stations    23331 non-null  object
 13  reference           6652 non-null   object
 14  web_link            1790 non-null   object
 15  population          22433 non-null  float64
 16  population_source   18102 non-null  object
 17  latitude            40098 non-null  float64
 18  longitude           40098 non-null  float64
 19  who_ms              40098 non-null  int64
dtypes: float64(9), int64(2), object(9)
memory usage: 6.1+ MB

In [ ]:
df1.shape

(40098, 20)

In [ ]:
df2=pd.read_csv(r"/content/WHO_DATASET2.csv")

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32191 entries, 0 to 32190
Data columns (total 15 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   who_region                              32190 non-null  object
 1   iso3                                    32191 non-null  object
 2   country_name                            32191 non-null  object
 3   city                                    32191 non-null  object
 4   year                                    32191 non-null  int64
 5   PM2.5 (μg/m3)                           15048 non-null  float64
 6   PM10 (μg/m3)                            21109 non-null  float64
 7   NO2 (μg/m3)                             22200 non-null  float64
 8   PM25 temporal coverage (%)              7275 non-null   float64
 9   PM10 temporal coverage (%)              5381 non-null   float64
 10  NO2 temporal coverage (%)               19890 non-null  float64
 11  Reference                               32186 non-null  object
 12  Number and type of monitoring stations  8758 non-null   object
 13  Version of the database                 32191 non-null  int64
 14  Status                                  0 non-null      float64
dtypes: float64(7), int64(2), object(6)
memory usage: 3.7+ MB

In [ ]:
df2.shape

(32191, 15)

In [ ]:
df1.head()

,who_region,iso3,country_name,city,year,version,pm10_concentration,pm25_concentration,no2_concentration,pm10_tempcov,pm25_tempcov,no2_tempcov,type_of_stations,reference,web_link,population,population_source,latitude,longitude,who_ms
0,4_Eur,ESP,Spain,A Coruna/ESP,2013.0,"V4.0 (2018), V4.0 (2018), V4.0 (2018), V4.0 (2...",23.238,11.491,28.841,87.0,46.0,93.0,"Urban, Urban, Suburban",NaN,NaN,246146.0,"manual, manual, manual, manual",43.367900,-8.418571,1
1,4_Eur,ESP,Spain,A Coruna/ESP,2014.0,"V6.0 (2023), V6.0 (2023), V6.0 (2023)",27.476,15.878,19.575,96.0,88.0,95.0,"Urban, Urban, Suburban",NaN,NaN,247604.0,NaN,43.368033,-8.418233,1
2,4_Eur,ESP,Spain,A Coruna/ESP,2015.0,"V6.0 (2023), V6.0 (2023), V6.0 (2023), V6.0...",25.515,14.004,22.731,98.0,71.0,98.0,"Urban, Urban, Suburban, Suburban",NaN,NaN,247604.0,NaN,43.370375,-8.422900,1
3,4_Eur,ESP,Spain,A Coruna/ESP,2016.0,"V6.0 (2023), V6.0 (2023), V6.0 (2023), V6.0...",23.057,13.160,20.204,98.0,98.0,98.0,"Urban, Urban, Suburban, Suburban",NaN,NaN,247604.0,NaN,43.370375,-8.422900,1
4,4_Eur,ESP,Spain,A Coruna/ESP,2017.0,"V6.0 (2023), V6.0 (2023), V6.0 (2023), V6.0...",26.849,14.114,21.543,97.0,97.0,98.0,"Urban, Urban, Suburban, Suburban",NaN,NaN,247604.0,NaN,43.370375,-8.422900,1

In [ ]:
df2.head()

,WHO Region,ISO3,WHO Country Name,City or Locality,Measurement Year,PM2.5 (μg/m3),PM10 (μg/m3),NO2 (μg/m3),PM25 temporal coverage (%),PM10 temporal coverage (%),NO2 temporal coverage (%),Reference,Number and type of monitoring stations,Version of the database,Status
0,Eastern Mediterranean Region,AFG,Afghanistan,Kabul,2019,119.77,NaN,NaN,18.0,NaN,NaN,"U.S. Department of State, United States Enviro...",NaN,2022,NaN
1,European Region,ALB,Albania,Durres,2015,NaN,17.65,26.63,NaN,NaN,83.961187,European Environment Agency (downloaded in 2021),NaN,2022,NaN
2,European Region,ALB,Albania,Durres,2016,14.32,24.56,24.78,NaN,NaN,87.932605,European Environment Agency (downloaded in 2021),NaN,2022,NaN
3,European Region,ALB,Albania,Elbasan,2015,NaN,NaN,23.96,NaN,NaN,97.853881,European Environment Agency (downloaded in 2021),NaN,2022,NaN
4,European Region,ALB,Albania,Elbasan,2016,NaN,NaN,26.26,NaN,NaN,96.049636,European Environment Agency (downloaded in 2021),NaN,2022,NaN

In [ ]:
# Print the columns of df1 and df2
print("Columns in df1:", df1.columns)
print("Columns in df2:", df2.columns)

Columns in df1: Index(['who_region', 'iso3', 'country_name', 'city', 'year', 'version',
       'pm10_concentration', 'pm25_concentration', 'no2_concentration',
       'pm10_tempcov', 'pm25_tempcov', 'no2_tempcov', 'type_of_stations',
       'reference', 'web_link', 'population', 'population_source', 'latitude',
       'longitude', 'who_ms'],
      dtype='object')
Columns in df2: Index(['WHO Region', 'ISO3', 'WHO Country Name', 'City or Locality',
       'Measurement Year', 'PM2.5 (μg/m3)', 'PM10 (μg/m3)', 'NO2 (μg/m3)',
       'PM25 temporal coverage (%)', 'PM10 temporal coverage (%)',
       'NO2 temporal coverage (%)', 'Reference',
       'Number and type of monitoring stations', 'Version of the database',
       'Status'],
      dtype='object')

common columns
df1: 'who_region', 'iso3', 'country_name', 'city', 'year'
df2: 'WHO Region', 'ISO3', 'WHO Country Name', 'City or Locality', 'Measurement Year'

In [ ]:
# Rename columns df2
df2.rename(columns={
    'WHO Region': 'who_region',
    'ISO3': 'iso3',
    'WHO Country Name': 'country_name',
    'City or Locality': 'city',
    'Measurement Year': 'year'
}, inplace=True)

In [ ]:
df2.head()

,who_region,iso3,country_name,city,year,PM2.5 (μg/m3),PM10 (μg/m3),NO2 (μg/m3),PM25 temporal coverage (%),PM10 temporal coverage (%),NO2 temporal coverage (%),Reference,Number and type of monitoring stations,Version of the database,Status
0,Eastern Mediterranean Region,AFG,Afghanistan,Kabul,2019,119.77,NaN,NaN,18.0,NaN,NaN,"U.S. Department of State, United States Enviro...",NaN,2022,NaN
1,European Region,ALB,Albania,Durres,2015,NaN,17.65,26.63,NaN,NaN,83.961187,European Environment Agency (downloaded in 2021),NaN,2022,NaN
2,European Region,ALB,Albania,Durres,2016,14.32,24.56,24.78,NaN,NaN,87.932605,European Environment Agency (downloaded in 2021),NaN,2022,NaN
3,European Region,ALB,Albania,Elbasan,2015,NaN,NaN,23.96,NaN,NaN,97.853881,European Environment Agency (downloaded in 2021),NaN,2022,NaN
4,European Region,ALB,Albania,Elbasan,2016,NaN,NaN,26.26,NaN,NaN,96.049636,European Environment Agency (downloaded in 2021),NaN,2022,NaN

In [ ]:
df1['city'] = df1['city'].str.strip()#That code is cleaning up the 'city' column in both df1 and df2 by removing leading and trailing
df2['city'] = df2['city'].str.strip()

In [ ]:
df1['year'] = df1['year'].fillna(-1).astype(int)#That code is handling missing values (NaN) in the 'year' column of both df1 and df2.

df2['year'] = df2['year'].fillna(-1).astype(int)

In [ ]:
df1 = df1.dropna(subset=['year'])# "This code removes missing values in the 'year' column from both DataFrames and then converts the 'year' values to integers."
df2 = df2.dropna(subset=['year'])
df1['year'] = df1['year'].astype(int)
df2['year'] = df2['year'].astype(int)

In [ ]:
df1['year'] = df1['year'].astype(int)
#astype(int) is used to convert the values in the 'year' column to integers.
df2['year'] = df2['year'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
print(df1['city'].unique())
print(df2['city'].unique())

['A Coruna/ESP' 'A La Shan Zuo Qi/CHN' 'Aachen/DEU' ... 'Zywiec/POL'
 '경기도/KOR' '虎英公园北/CHN']
['Kabul' 'Durres' 'Elbasan' ... 'Waterberg' 'West Coast' 'West Rand']

In [ ]:
#data merging

merged_df = pd.merge(df1, df2, on=['who_region', 'iso3', 'country_name', 'city', 'year'], how='inner')

In [ ]:
merged_df.head()

Empty DataFrame
Columns: [who_region, iso3, country_name, city, year, version, pm10_concentration, pm25_concentration, no2_concentration, pm10_tempcov, pm25_tempcov, no2_tempcov, type_of_stations, reference, web_link, population, population_source, latitude, longitude, who_ms, PM2.5 (μg/m3), PM10 (μg/m3), NO2 (μg/m3), PM25 temporal coverage (%), PM10 temporal coverage (%), NO2 temporal coverage (%), Reference, Number and type of monitoring stations, Version of the database, Status]
Index: []

[0 rows x 30 columns]

In [ ]:
df1['year'] = df1['year'].fillna(-1).astype(int)
df2['year'] = df2['year'].fillna(-1).astype(int)

In [ ]:
#data merging
merged_df1 = pd.merge(df1, df2, on=['who_region', 'iso3', 'country_name', 'city', 'year'], how='inner')

In [ ]:
merged_df1.head()

Empty DataFrame
Columns: [who_region, iso3, country_name, city, year, version, pm10_concentration, pm25_concentration, no2_concentration, pm10_tempcov, pm25_tempcov, no2_tempcov, type_of_stations, reference, web_link, population, population_source, latitude, longitude, who_ms, PM2.5 (μg/m3), PM10 (μg/m3), NO2 (μg/m3), PM25 temporal coverage (%), PM10 temporal coverage (%), NO2 temporal coverage (%), Reference, Number and type of monitoring stations, Version of the database, Status]
Index: []

[0 rows x 30 columns]

In [ ]:
merged_df2 = pd.merge(df1, df2, on=['who_region', 'iso3', 'country_name', 'city', 'year'], how='outer')

In [ ]:
merged_df2.head()

,who_region,iso3,country_name,city,year,version,pm10_concentration,pm25_concentration,no2_concentration,pm10_tempcov,...,PM2.5 (μg/m3),PM10 (μg/m3),NO2 (μg/m3),PM25 temporal coverage (%),PM10 temporal coverage (%),NO2 temporal coverage (%),Reference,Number and type of monitoring stations,Version of the database,Status
0,1_Afr,BEN,Benin,Cotonou/BEN,2019,"V6.0 (2023), V6.0 (2023)",NaN,NaN,98.960,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1_Afr,BEN,Benin,Cotonou/BEN,2020,"V6.0 (2023), V6.0 (2023), V6.0 (2023)",9.1,7.7,129.635,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1_Afr,CMR,Cameroon,Bafoussam/CMR,2012,V3.0 (2016),105.0,67.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1_Afr,CMR,Cameroon,Bamenda/CMR,2012,V3.0 (2016),141.0,132.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1_Afr,CMR,Cameroon,Yaoude/CMR,2012,V3.0 (2016),65.0,49.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
merged_df2.shape

(72289, 30)

In [ ]:
merged_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72289 entries, 0 to 72288
Columns: 360 entries, iso3 to station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban
dtypes: bool(338), float64(18), int64(1), object(3)
memory usage: 35.4+ MB

In [ ]:
#exporting merged dataframe
#We're exporting the merged DataFrame to an Excel file named merged_data.xlsx without including the index column."
merged_df.to_excel('merged_data.xlsx', index=False)

In [ ]:
cols_to_drop = ['version', 'reference', 'web_link', 'population_source',
                'Reference', 'Number and type of monitoring stations']

merged_df2.drop(columns=cols_to_drop, inplace=True)# inplace=True makes changes directly to the original DataFrame instead of creating a new one.

KeyError: "['version', 'reference', 'web_link', 'population_source', 'Reference', 'Number and type of monitoring stations'] not found in axis"

In [ ]:
merged_df2

,who_region,iso3,country_name,city,year,pm10_concentration,pm25_concentration,no2_concentration,pm10_tempcov,pm25_tempcov,...,longitude,who_ms,PM2.5 (μg/m3),PM10 (μg/m3),NO2 (μg/m3),PM25 temporal coverage (%),PM10 temporal coverage (%),NO2 temporal coverage (%),Version of the database,Status
0,1_Afr,BEN,Benin,Cotonou/BEN,2019,NaN,NaN,98.960,NaN,NaN,...,2.332126,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1_Afr,BEN,Benin,Cotonou/BEN,2020,9.1,7.7,129.635,67.0,67.0,...,2.361751,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1_Afr,CMR,Cameroon,Bafoussam/CMR,2012,105.0,67.0,NaN,NaN,NaN,...,10.416400,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1_Afr,CMR,Cameroon,Bamenda/CMR,2012,141.0,132.0,NaN,NaN,NaN,...,10.166700,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1_Afr,CMR,Cameroon,Yaoude/CMR,2012,65.0,49.0,NaN,NaN,NaN,...,11.516700,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72284,Western Pacific Region,VNM,Viet Nam,Nha Trang,2014,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,12.00,NaN,NaN,NaN,NaN,2018.0,NaN
72285,Western Pacific Region,VNM,Viet Nam,Nha Trang,2015,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.00,NaN,NaN,NaN,NaN,2018.0,NaN
72286,Western Pacific Region,VNM,Viet Nam,Viet Tri,2013,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27.00,NaN,NaN,NaN,NaN,2018.0,NaN
72287,Western Pacific Region,VNM,Viet Nam,Viet Tri,2014,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,22.00,NaN,NaN,NaN,NaN,2018.0,NaN
72288,NaN,LIE,Liechtenstein,Vaduz,2010,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,17.88,23.59,NaN,96.164,98.265,2022.0,NaN

In [ ]:
merged_df2.isnull().sum()  # Displays the count of missing values per column

iso3                                                                                                                                                                                                                          0
country_name                                                                                                                                                                                                                  0
city                                                                                                                                                                                                                          0
year                                                                                                                                                                                                                          0
pm10_concentration                                                                                                                                                                                                        43617
                                                                                                                                                                                                                          ...
station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Suburban, Urban, Urban, Suburban, Rural                       0
station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban                                                  0
station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban                                           0
station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban                             0
station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban        0
Length: 360, dtype: int64

In [ ]:
merged_df2

,iso3,country_name,city,year,pm10_concentration,pm25_concentration,no2_concentration,pm10_tempcov,pm25_tempcov,no2_tempcov,...,"station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Suburban, Urban, Urban, Urban, Suburban","station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Suburban, Urban, Urban, Urban, Suburban, Urban","station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban","station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban","station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban","station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Suburban, Urban, Urban, Suburban, Rural","station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban","station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban","station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban","station_type_Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban, Urban"
0,BEN,Benin,Cotonou/BEN,2019,NaN,NaN,3.099233,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
1,BEN,Benin,Cotonou/BEN,2020,9.1,-0.653583,4.286136,67.0,67.0,NaN,...,False,False,False,False,False,False,False,False,False,False
2,CMR,Cameroon,Bafoussam/CMR,2012,105.0,2.736999,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
3,CMR,Cameroon,Bamenda/CMR,2012,141.0,6.453488,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
4,CMR,Cameroon,Yaoude/CMR,2012,65.0,1.707817,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72284,VNM,Viet Nam,Nha Trang,2014,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
72285,VNM,Viet Nam,Nha Trang,2015,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
72286,VNM,Viet Nam,Viet Tri,2013,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
72287,VNM,Viet Nam,Viet Tri,2014,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
72288,LIE,Liechtenstein,Vaduz,2010,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False